require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/HashEachMethods:
  Enabled: false
